name: flowai
description: "An AI-powered personal productivity coach."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated to a modern SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.0 # Core Firebase SDK
  cloud_firestore: ^6.0.3 # Firestore database

  # State Management
  provider: ^6.1.2 # For state management

  # UI & Utilities
  fl_chart: ^1.1.1 # For analytics charts
  intl: ^0.20.2 # For date/time formatting
  uuid: ^4.4.0 # For generating unique task IDs

  # Notifications
  flutter_local_notifications: ^19.5.0 # For mobile notifications

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true